server:
  port: 10010
spring:
  application:
    name: getway
zuul:
  routes:
    hehe:
      path: /user-consumer/**
      url: http://127.0.0.1:8080

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka