server:
  port: 10010
spring:
  application:
    name: getway
zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    user-consumer:
      path: /user-consumer/**
      serverId: user-consumer
    user-service:
      path: /user-service/**
      serverId: user-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  ReadTimeout: 60000
  ConnectTimeout: 60000


