server:
  port: 8080
spring:
  application:
    name: user-consumer
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: chen123
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

ribbon:
  ConnectionTimeout:5000
  ReadTimeOut:2000
Feign:
  hystrix:
    enabled: true
